# Generated by Django 5.1 on 2024-08-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helixApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
